"""add foreign key to review

Revision ID: 198c55033478
Revises: c371cb67e875
Create Date: 2024-04-06 20:35:07.500883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198c55033478'
down_revision = 'c371cb67e875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_employee_id_employees', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_employee_id_employees', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
